name: Supplier Service CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:

  PROJECT_ID: ${{secrets.PROJECT_ID}}
  GKE_CLUSTER: k8s-docker-spring-boot
  GKE_ZONE: us-central1-c

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file 

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: pamuditha98/spring-boot-docker
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
  Deploy:

    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: kubectl - Google Cloud GKE cluster
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{env.PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{secrets.GKE_SA_KEY}}
        CLUSTER_NAME: ${{env.GKE_CLUSTER}}
        ZONE_NAME: ${{env.GKE_ZONE}}
      with:
        args: apply -f docker-k8s-spring-boot
